export const initialProducts = [
  {
    id: 'p01',
    handle: 'studio-wireless-headphones',
    name: 'Studio Wireless Headphones',
    category: 'Tech & Audio',
    price: 2499,
    image: 'headphones.png',
    label: 'The everyday edit',
    color: 'Ivory',
    colors: ['Ivory'],
    stock: 12,
    description: 'A little quiet. A lot of good sound. A comfortable over-ear companion for your playlists, work sessions and slower mornings.',
    details: ['Cushioned over-ear design', 'Wireless listening with simple controls', 'Headphones and charging cable included'],
    keywords: ['headphone', 'headphones', 'wireless headphones', 'head phone', 'over ear', 'sony', 'jbl', 'bluetooth headset', 'earphone', 'audio'],
    note: 'Sample product. Final specifications and availability will be confirmed on WhatsApp.'
  },
  {
    id: 'p02',
    handle: 'blend-go-portable-blender',
    name: 'Blend & Go Portable Blender',
    category: 'Kitchen & Home',
    price: 1299,
    image: 'blender.png',
    label: 'A fresh little find',
    color: 'Sage',
    colors: ['Sage'],
    stock: 10,
    description: 'Your morning routine, with a fresh twist. A compact blender made for colourful smoothies and easy kitchen moments.',
    details: ['Compact, carry-friendly design', 'Clear blending cup with screw-on lid', 'Blender and charging cable included'],
    keywords: ['blender', 'portable blender', 'juicer', 'smoothie maker', 'mixer', 'shake', 'kitchen'],
    note: 'Sample product. Capacity and charging specifications are illustrative until confirmed.'
  },
  {
    id: 'p03',
    handle: 'pocket-beat-speaker',
    name: 'Pocket Beat Speaker',
    category: 'Tech & Audio',
    price: 999,
    image: 'speaker.png',
    label: 'Take your music along',
    color: 'Terracotta',
    colors: ['Terracotta'],
    stock: 8,
    description: 'Small enough to come along. Full of personality. Bring a little soundtrack to your desk, kitchen or weekend away.',
    details: ['Compact fabric-covered body', 'Convenient carrying loop', 'Speaker and charging cable included'],
    keywords: ['speaker', 'speakers', 'bluetooth speaker', 'pocket beat', 'soundbox', 'jbl speaker', 'wireless speaker', 'bass'],
    note: 'Sample product. Battery life and water resistance are not yet verified.'
  },
  {
    id: 'p04',
    handle: 'everyday-wireless-earbuds',
    name: 'Everyday Wireless Earbuds',
    category: 'Tech & Audio',
    price: 899,
    image: 'earbuds.png',
    label: 'Small. Simple. Wireless.',
    color: 'Ivory',
    colors: ['Ivory'],
    stock: 15,
    description: 'For your daily soundtrack and the calls in between. Simple wireless earbuds with a tidy pocket-sized charging case.',
    details: ['In-ear wireless design', 'Compact charging case', 'Earbuds, case and charging cable included'],
    keywords: ['airpod', 'airpods', 'earbud', 'earbuds', 'earphone', 'earphones', 'tws', 'air pod', 'air pods', 'buds', 'wireless earbuds', 'in ear', 'bluetooth buds', 'apple airpods'],
    note: 'Unbranded sample product. Not affiliated with Apple or any other electronics brand.'
  },
  {
    id: 'p05',
    handle: 'little-glow-table-lamp',
    name: 'Little Glow Table Lamp',
    category: 'Kitchen & Home',
    price: 1499,
    image: 'lamp.png',
    label: 'Set a softer mood',
    color: 'Butter',
    colors: ['Butter'],
    stock: 6,
    description: 'Make a little corner feel like home. A softly sculpted table lamp for bedside reading, evening unwinding and everyday warmth.',
    details: ['Sculptural mushroom silhouette', 'Compact table-top design', 'One lamp included'],
    keywords: ['lamp', 'table lamp', 'desk lamp', 'light', 'night lamp', 'bedside lamp', 'glow lamp', 'lighting'],
    note: 'Sample product. Dimensions, power source and brightness will be confirmed before ordering.'
  },
  {
    id: 'p06',
    handle: 'daylight-smart-watch',
    name: 'Daylight Smart Watch',
    category: 'Daily Essentials',
    price: 1799,
    image: 'watch.png',
    label: 'Made for your routine',
    color: 'Sand',
    colors: ['Sand'],
    stock: 9,
    description: 'A clean face and an easygoing strap. A considered everyday accessory that fits right into your daily routine.',
    details: ['Rounded rectangular watch face', 'Soft adjustable strap', 'Watch and charging accessory included'],
    keywords: ['smart watch', 'smartwatch', 'watch', 'apple watch', 'smart band', 'fitness watch', 'wrist watch', 'digital watch'],
    note: 'Sample product. Compatibility and available features need confirmation. No medical functionality is claimed.'
  },
  {
    id: 'p07',
    handle: 'magnetic-strip-tape-roll',
    name: 'Self-Adhesive Magnetic Tape',
    category: 'Daily Essentials',
    price: 499,
    image: 'magnatictape.png',
    label: 'Quick home organizer',
    color: 'Black',
    colors: ['Black'],
    stock: 25,
    description: 'Heavy-duty flexible magnetic strip tape with strong adhesive backing for DIY crafts, organizing tools, and whiteboard fixing.',
    details: ['Flexible magnetic strip with strong backing', 'Easy to cut with standard scissors', 'Dual rolls included in pack'],
    keywords: ['magnetic tape', 'tape', 'strip', 'adhesive', 'magnet', 'craft tape', 'magnetic strip'],
    note: 'Genuine sample product. Length and holding strength confirmed on order.'
  },
  {
    id: 'p08',
    handle: 'portable-mini-air-cooler',
    name: 'Compact Mini Desk Cooler',
    category: 'Kitchen & Home',
    price: 1199,
    image: 'minicooler.png',
    label: 'Instant personal breeze',
    color: 'White',
    colors: ['White'],
    stock: 14,
    description: 'Portable personal desktop air cooler fan with multi-speed adjustment, whisper-quiet motor, and low power consumption.',
    details: ['Compact desk-friendly form factor', 'Low noise cooling fan grille', 'USB powered cable included'],
    keywords: ['cooler', 'air cooler', 'mini cooler', 'desk cooler', 'ac', 'fan', 'portable fan', 'desk fan', 'mini ac'],
    note: 'Sample product. Cooling reach and power ratings confirmed before dispatch.'
  },
  {
    id: 'p09',
    handle: 'insulated-sports-water-bottle',
    name: 'Active Sports Water Bottle',
    category: 'Daily Essentials',
    price: 699,
    image: 'waterbottle.png',
    label: 'Hydration on the move',
    color: 'Crimson Red',
    colors: ['Crimson Red'],
    stock: 18,
    description: 'BPA-free durable sports water bottle with leak-proof flip cap, carrying loop lanyard, and clear hydration capacity.',
    details: ['BPA-free food grade durable build', 'Ergonomic leak-proof flip lid with carry cord', 'Lightweight active lifestyle companion'],
    keywords: ['water bottle', 'bottle', 'flask', 'sports bottle', 'thermos', 'gym bottle', 'cello bottle'],
    note: 'Sample product. Volume capacity confirmed on WhatsApp confirmation.'
  }
];
